### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by guna799**
Please review and accept the Pull request, Thnx!

### CODE REVIEW

**Review by IppiliPraveen — APPROVED** [review]
Approved

**Comment by IppiliPraveen** [comment]
@guna799 changes are Merged

**Comment by guna799** [comment]
Thanks @IppiliPraveen

**Comment by IppiliPraveen** [comment]
Hi @Guna Vardhan ***@***.***> ,

Can please continue on this project changes. And keep me update on the
progress.

Thanks & Regards,

Sai Praveen Ippili |  Software Engineer
Exciting times...infinite possibilities…

Cell : 7093510019

www.infinite.com

**Pull request merged**
